export const REASON_CODES = {
  INVALID_STRUCTURE: "INVALID_STRUCTURE",
  INVALID_NODE_KIND: "INVALID_NODE_KIND",
  INVALID_RELATIONSHIP_TYPE: "INVALID_RELATIONSHIP_TYPE",
  INVALID_RECEIPT_TYPE: "INVALID_RECEIPT_TYPE",
  PROVENANCE_REQUIRED: "PROVENANCE_REQUIRED",
  PROVENANCE_UNRESOLVED: "PROVENANCE_UNRESOLVED",
  CANONICALIZATION_FAILED: "CANONICALIZATION_FAILED",
  RECEIPT_PARENT_MISSING: "RECEIPT_PARENT_MISSING",
  RECEIPT_IDENTITY_CONFLICT: "RECEIPT_IDENTITY_CONFLICT",
  AUTHORITY_MISSING: "AUTHORITY_MISSING",
  AUTHORITY_GRANT_INVALID: "AUTHORITY_GRANT_INVALID",
  AUTHORITY_RECIPIENT_MISMATCH: "AUTHORITY_RECIPIENT_MISMATCH",
  AUTHORITY_CAPABILITY_MISMATCH: "AUTHORITY_CAPABILITY_MISMATCH",
  AUTHORITY_SCOPE_MISMATCH: "AUTHORITY_SCOPE_MISMATCH",
  AUTHORITY_PURPOSE_MISMATCH: "AUTHORITY_PURPOSE_MISMATCH",
  AUTHORITY_NOT_YET_VALID: "AUTHORITY_NOT_YET_VALID",
  AUTHORITY_EXPIRED: "AUTHORITY_EXPIRED",
  AUTHORITY_EXHAUSTED: "AUTHORITY_EXHAUSTED",
  AUTHORITY_LINEAGE_INVALID: "AUTHORITY_LINEAGE_INVALID",
  AUTHORITY_ISSUER_MISMATCH: "AUTHORITY_ISSUER_MISMATCH",
  AUTHORITY_TIME_INVALID: "AUTHORITY_TIME_INVALID",
  DISCLOSURE_NOT_PERMITTED: "DISCLOSURE_NOT_PERMITTED",
} as const;

export type ReasonCode = typeof REASON_CODES[keyof typeof REASON_CODES];

export type ValidationResult =
  | { status: "valid"; reasonCodes: [] }
  | { status: "invalid"; reasonCodes: ReasonCode[] };

export const valid = (): ValidationResult => ({ status: "valid", reasonCodes: [] });
export const invalid = (...reasonCodes: ReasonCode[]): ValidationResult => ({ status: "invalid", reasonCodes });
